/**
 * Block Kit admin: the "AVDEB Products" overview page and the dashboard widget.
 * The settings form itself is generated by EmDash from `settingsSchema`.
 */

import type { RouteContext } from "emdash";

import { keyProblem, maxLimit } from "./catalog.ts";
import type { CatalogClient, ClientStats, KeyInfo } from "./client.ts";
import { AFFILIATE_URL, DOCS_URL, PARTNER_DASHBOARD_URL } from "./constants.ts";
import { clientFor, loadSettings } from "./routes.ts";
import type { ResolvedSettings } from "./settings.ts";
import { formatPrice } from "./view.ts";

type Block = Record<string, unknown>;
export interface BlockResult {
	blocks: Block[];
	toast?: { message: string; type: "success" | "error" | "info" };
}

export const WIDGET_ID = "status";

function isRecord(v: unknown): v is Record<string, unknown> {
	return typeof v === "object" && v !== null && !Array.isArray(v);
}

/** "3 min ago" style relative time. */
export function ago(then: number | null, now: number): string {
	if (!then) return "never";
	const s = Math.max(0, Math.round((now - then) / 1000));
	if (s < 60) return "just now";
	const m = Math.round(s / 60);
	if (m < 60) return `${m} min ago`;
	const h = Math.round(m / 60);
	if (h < 48) return `${h} h ago`;
	return `${Math.round(h / 24)} days ago`;
}

/** Connection status as a banner (or null when everything is fine). */
export function connectionBanner(settings: ResolvedSettings, info: KeyInfo | null): Block | null {
	const problem = keyProblem(settings.rawApiKey);
	if (problem === "publishable") {
		return {
			type: "banner",
			variant: "error",
			title: "That is a publishable key",
			description:
				"Publishable keys (avdeb_pk_…) are for the browser embed. This plugin calls AVDEB from your server and needs a secret key that starts with avdeb_sk_.",
		};
	}
	if (problem === "malformed") {
		return {
			type: "banner",
			variant: "error",
			title: "The saved key doesn't look like an AVDEB secret key",
			description: "Expected avdeb_sk_ followed by 32 letters and digits. Products still show, without your key.",
		};
	}
	if (info && !info.ok) {
		return {
			type: "banner",
			variant: "error",
			title: "AVDEB did not accept the secret key",
			description: `${info.error}. Check the key in the partner dashboard, or remove it to use a referral code instead.`,
		};
	}
	if (info?.ok && !info.owner.ref) {
		return {
			type: "banner",
			variant: "alert",
			title: "Connected, but your account has no referral code yet",
			description: "Links work but aren't credited to you. Creators get the code of their linked affiliate account.",
		};
	}
	if (!settings.apiKey && !settings.refCode) {
		return {
			type: "banner",
			variant: "alert",
			title: "Links aren't credited to you yet",
			description:
				"Add a secret key (recommended) or your referral code in Settings. Without either, embeds show plain AVDEB links.",
		};
	}
	return null;
}

function connectionFields(settings: ResolvedSettings, info: KeyInfo | null): Block {
	const fields: Array<{ label: string; value: string }> = [];
	if (info?.ok) {
		fields.push({ label: "Connected as", value: `${info.owner.name || "AVDEB partner"} (${info.owner.type || "partner"})` });
		fields.push({ label: "Referral code", value: info.owner.ref || "—" });
	} else {
		fields.push({ label: "Connection", value: settings.apiKey ? "Secret key (not verified)" : "No key — public catalog" });
		fields.push({ label: "Referral code", value: settings.refCode || "—" });
	}
	fields.push({ label: "Products per embed", value: `up to ${maxLimit(settings.apiKey !== "" && info?.ok === true)}` });
	fields.push({ label: "Cache", value: `${settings.cacheMinutes} min, last good copy kept 7 days` });
	return { type: "fields", fields };
}

function statsBlock(stats: ClientStats, now: number): Block {
	return {
		type: "stats",
		items: [
			{ label: "Cached embeds", value: stats.cachedQueries, description: "distinct queries" },
			{ label: "AVDEB requests", value: stats.requests, description: `last ${ago(stats.lastFetchAt, now)}` },
			{
				label: "Errors",
				value: stats.errors,
				description: stats.lastError ? `${stats.lastError} (${ago(stats.lastErrorAt, now)})` : "none",
			},
		],
	};
}

function actions(compact: boolean): Block {
	const elements: Block[] = [
		{ type: "button", action_id: "refresh_cache", label: "Refresh products now", style: "primary" },
	];
	if (!compact) elements.push({ type: "button", action_id: "test_connection", label: "Test connection" });
	elements.push({ type: "link", label: "Settings", target: { kind: "plugin-settings" }, appearance: "secondary" });
	if (!compact) {
		elements.push({ type: "link", label: "Get a secret key", target: { kind: "external", url: PARTNER_DASHBOARD_URL } });
		elements.push({ type: "link", label: "Become an affiliate", target: { kind: "external", url: AFFILIATE_URL } });
	}
	return { type: "actions", elements };
}

const TEMPLATE_SNIPPET = `---
import { AvdebProducts, AvdebProduct, AvdebButton } from "emdash-plugin-avdeb/ui";
---

<AvdebProducts creator="your-slug" layout="carousel" limit={8} heading="From my shop" />
<AvdebProducts tag="stickers" layout="grid" columns={4} cardStyle="outline" />
<AvdebProducts q="cat stickers" layout="list" limit={3} />
<AvdebProduct handle="cat-sticker" variant="hero" badge="Editor's pick" note="I use it every day." />
<AvdebButton href="/creators/your-slug/" label="Visit my shop" variant="outline" />`;

const CSS_SNIPPET = `/* Every value is a CSS custom property; selectors use :where(), so yours always win. */
.avdeb {
  --avdeb-accent: #4d7f5a;      /* prices, badges, buttons */
  --avdeb-radius: 20px;
  --avdeb-gap: 1.25rem;
  --avdeb-card-bg: #fff;
  --avdeb-font-title: "Fraunces", serif;
}`;

function usage(): Block[] {
	return [
		{
			type: "accordion",
			label: "Add products to a post",
			default_open: false,
			blocks: [
				{
					type: "context",
					text: "In any rich-text field type “/” and choose AVDEB Products, AVDEB Product or AVDEB Button. Paste a creator, category or product link — the source is detected automatically.",
				},
			],
		},
		{
			type: "accordion",
			label: "Use in Astro templates",
			default_open: false,
			blocks: [{ type: "code", language: "tsx", code: TEMPLATE_SNIPPET }],
		},
		{
			type: "accordion",
			label: "Match your theme",
			default_open: false,
			blocks: [{ type: "code", language: "css", code: CSS_SNIPPET }],
		},
		{ type: "actions", elements: [{ type: "link", label: "Documentation", target: { kind: "external", url: DOCS_URL } }] },
	];
}

async function previewTable(client: CatalogClient, settings: ResolvedSettings, info: KeyInfo | null): Promise<Block[]> {
	const creator = info?.ok ? info.owner.creatorSlug : "";
	const out = await client.products({ ...(creator ? { creator } : {}), limit: 6 });
	return [
		{ type: "header", text: creator ? "Your newest products" : "Newest on AVDEB" },
		{
			type: "table",
			page_action_id: "preview_page",
			columns: [
				{ key: "title", label: "Product" },
				{ key: "price", label: "Price" },
				{ key: "creator", label: "Designer" },
				{ key: "handle", label: "Handle", format: "code" },
			],
			rows: out.products.map((p) => ({
				title: p.title,
				price: formatPrice(p.price, p.currency) ?? "—",
				creator: p.creator?.name ?? "—",
				handle: p.handle,
			})),
			empty_text: out.error ? `AVDEB could not be reached: ${out.error}` : "No products found.",
		},
		{
			type: "context",
			text: settings.refCode || info?.ok ? "Every product link on your site carries your referral code and rel=\"sponsored\"." : "Links are plain until you add a key or referral code.",
		},
	];
}

export async function overviewPage(ctx: RouteContext, now = Date.now()): Promise<Block[]> {
	const settings = await loadSettings(ctx);
	const client = clientFor(ctx, settings);
	const info = await client.keyInfo();
	const banner = connectionBanner(settings, info);
	return [
		{ type: "header", text: "AVDEB Products" },
		{
			type: "context",
			text: "Embed AVDEB products — a creator's shop, a category, a search or single products — with your referral code on every link.",
		},
		...(banner ? [banner] : []),
		connectionFields(settings, info),
		statsBlock(await client.stats(), now),
		actions(false),
		{ type: "divider" },
		...(await previewTable(client, settings, info)),
		{ type: "divider" },
		...usage(),
	];
}

export async function widget(ctx: RouteContext, now = Date.now()): Promise<Block[]> {
	const settings = await loadSettings(ctx);
	const client = clientFor(ctx, settings);
	const info = await client.keyInfo();
	const banner = connectionBanner(settings, info);
	const stats = await client.stats();
	return [
		...(banner ? [banner] : []),
		{
			type: "fields",
			fields: [
				{ label: "Referral code", value: (info?.ok ? info.owner.ref : settings.refCode) || "—" },
				{ label: "Last refresh", value: ago(stats.lastFetchAt, now) },
			],
		},
		actions(true),
	];
}

/** The `admin` route: page_load / block_action for the overview page and the widget. */
export async function adminRoute(ctx: RouteContext): Promise<BlockResult> {
	const input = isRecord(ctx.input) ? ctx.input : {};
	const page = typeof input.page === "string" ? input.page : "/";
	const isWidget = page === `widget:${WIDGET_ID}`;
	const render = () => (isWidget ? widget(ctx) : overviewPage(ctx));

	if (input.type === "block_action") {
		const settings = await loadSettings(ctx);
		const client = clientFor(ctx, settings);
		if (input.action_id === "refresh_cache") {
			await client.flush();
			return { blocks: await render(), toast: { type: "success", message: "Products will be re-fetched from AVDEB" } };
		}
		if (input.action_id === "test_connection") {
			await client.flush();
			const info = await client.keyInfo();
			const toast: BlockResult["toast"] = !settings.apiKey
				? { type: "info", message: settings.refCode ? `No key saved — using referral code ${settings.refCode}` : "No key saved" }
				: info?.ok
					? { type: "success", message: `Connected as ${info.owner.name || "AVDEB partner"}` }
					: { type: "error", message: `Key not accepted: ${info?.error ?? "unknown error"}` };
			return { blocks: await render(), toast };
		}
	}
	return { blocks: await render() };
}
